apiVersion: v2
name: sd-trade-order-management
description: "BIAN Service Domain: Trade Order Management (Manage pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Securities"
  bian/asset-type: "Trade Order"
  bian/control-record: "Trade Order Management Plan"
